services:
  NotionAutoRepeat:
    environment:
      - NOTION_SECRET
      - NOTION_DATABASE_ID
      - REQUEST_INTERVAL_IN_SECONDS
    image: notionautorepeat
    build:
        context: .
        dockerfile: Dockerfile