services:
  NotionAutoRepeat:
    environment:
      - NOTION_SECRET = secret
      - NOTION_DATABASE_ID = database_id
      - REQUEST_INTERVAL_IN_SECONDS = 60
    image: notionautorepeat
    build:
        context: .
        dockerfile: Dockerfile