services:
  NotionAutoRepeat:
    environment:
      - NOTION_SECRET = secret
      - NOTION_DATABASE_ID = database_id
    image: notionautorepeat
    build:
        context: .
        dockerfile: Dockerfile